fix: less verbose permissioning

diff --git a/plugin/scripts/makepkg b/plugin/scripts/makepkg
--- a/plugin/scripts/makepkg
+++ b/plugin/scripts/makepkg
@@ -379,8 +379,11 @@ else
   echo
 fi
 if [ "$CHOWN" = "y" ]; then
-  find . -type d -exec sudo chmod -v 755 {} \;
-  find . -type d -exec sudo chown -v 0:0 {} \;
+  # Set strict mode and fail if commands fail
+  set -e
+  find . -type d -exec sudo chmod 755 {} + || exit 1
+  find . -type d -exec sudo chown 0:0 {} + || exit 1
+  set +e
 fi
 
 # Ensure that the 'root' of the package is chmod 755 because
