fix: proper file replacements

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -205,7 +205,17 @@ jobs:
           export NODEJS_FILENAME=${{ steps.download-nodejs.outputs.NODEJS_FILENAME }}
           export NODEJS_SHA256=${{ steps.download-nodejs.outputs.NODEJS_SHA256 }}
           export NGHTTP3_FILENAME=${{ steps.download-nghttp3.outputs.NGHTTP3_FILENAME }}
-          export NGHTTP3_SHA256=${{ steps.download-nghttp3.outputs.NGHTTP3_SHA256 }}
+          if [ -z "${API_VERSION}" ] || 
+            [ -z "${API_MD5}" ] || 
+            [ -z "${API_SHA256}" ] || 
+            [ -z "${NODEJS_FILENAME}" ] || 
+            [ -z "${NODEJS_SHA256}" ] || 
+            [ -z "${NGHTTP3_FILENAME}" ] || 
+            [ -z "${NGHTTP3_SHA256}" ]; then
+            echo "Error: One or more required variables are not set."
+            exit 1
+          fi
+
           bash ./pkg_build.sh s ${{github.event.pull_request.number}}
           bash ./pkg_build.sh p
       - name: Upload binary txz and plg to Github artifacts
